version: '3.2'
services:
    gateway:
        build: ./gateway
        ports:
            - "4000:4000"
        depends_on: 
            - target-db

    astraea:
        build: ./astraea
        ports:
            - "5000:5000"
        depends_on:
            - log-db

    log-db:
        command: ["mysqld", "--innodb-use-native-aio=0"]
        image: sconecuratedimages/apps:mariadb-10-alpine   
        expose:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: 'TEST_PASSWORD'       
            MYSQL_DATABASE: 'audit'
            MYSQL_USER: 'tpccuser'
            MYSQL_PASSWORD: 'TEST_PASSWORD'

    target-db:
        command: ["mysqld", "--innodb-use-native-aio=0"]
        image: sconecuratedimages/apps:mariadb-10-alpine   
#        volumes:
#            - data:/var/lib/mysql/data2
        expose:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: 'TEST_PASSWORD'
            MYSQL_DATABASE: 'target'
            MYSQL_USER: 'tpccuser'
            MYSQL_PASSWORD: 'TEST_PASSWORD'

