version: '2.1'
services:
    client:
        container_name: client
        build: ./client
        ports:
            - "6000:6000"
        volumes:
            - ./client/received:/received
    gateway:
        container_name: gateway
        build: ./gateway
        ports:
            - "4000:4000"
        depends_on: 
            - target-db

        cpu_quota: 50000
        cpu_period: 20ms            
        volumes:
            - ./gateway/data:/data
          
    astraea:
        container_name: astraea
        build: ./astraea
        ports:
            - "5000:5000"
        depends_on:
            - log-db
            - target-db
            - amcs
        cpu_quota: 50000
        cpu_period: 20ms

 

    amcs:
        container_name: amcs
#        build: ./amcs
        image: astraea/amcs:0.2
        ports:
            - "4444:4444" 
        devices:
            - "/dev/isgx:/dev/isgx"
            - "/dev/mei0:/dev/mei0"

 
    log-db:
        container_name: log-db
        command: ["mysqld", "--innodb-use-native-aio=0"]
        image: sconecuratedimages/apps:mariadb-10-alpine   
        expose:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: 'TEST_PASSWORD'       
            MYSQL_DATABASE: 'log'
            MYSQL_USER: 'tpccuser'
            MYSQL_PASSWORD: 'TEST_PASSWORD'

    target-db:
        container_name: target-db
        command: ["mysqld", "--innodb-use-native-aio=0"]
        image: sconecuratedimages/apps:mariadb-10-alpine   
#        volumes:
#            - data:/var/lib/mysql/data2
#        expose:
#            - "3306"
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 'TEST_PASSWORD'
            MYSQL_DATABASE: 'target'
            MYSQL_USER: 'tpccuser'
            MYSQL_PASSWORD: 'TEST_PASSWORD'

