FROM silicon_base
MAINTAINER Dana Kuban

# add client.cpp
ADD client.cpp http_request_helper.h /

# generate symbols.hh
RUN /bin/iod_generate_symbols client.cpp symbols_client.hh

# compile app
RUN clang++ -std=c++14 -I /include client.cpp -lmicrohttpd -lcurl -pthread -o client

# create script for entering container -> starting the app
RUN echo "/client" > run_example.sh && chmod +x run_example.sh

# create folder data
RUN mkdir data

EXPOSE 12346

ENTRYPOINT ["sh", "-c", "/run_example.sh"]
#CMD tail -f /dev/null