setwd("/Users/danakuban/Documents/AFT/astraea-gateway/gateway/data/")
data <- read.csv("summary.csv", header=TRUE, sep=";")
attach(data)
heading = paste("type=","l") 
pdf(file = "graph.pdf")
plot(requests,w, type="n",xlab="Number of Requests",ylab="Response Time in ms",main="Duration", cex=0.8)
lines(requests, r, type="l") 
lines(requests, w, type="l") 
lines(requests, rw, type="l") 
points(requests,w,col=2,pch=5)
points(requests,rw,col=3,pch=2)
points(requests,r,col=1,pch=1)
legend(10,800,c("r","w","rw"),col=c(1,2,3),pch=c(1,5,2), cex=0.8)
detach(data)
dev.off()