FROM sconecuratedimages/utils:intel-sgx-sdk-latest

MAINTAINER Gabriel Fernandez <gabrielpfernandez@gmail.com>

RUN apt update && apt-get install -y apt-utils make kmod pkg-config alien wget cmake pkg-config uuid-dev libxml2-dev libsystemd-dev lib32gcc1 lib32stdc++6 libc6-i386 ca-certificates build-essential ocaml automake autoconf libtool wget python libssl-dev libcurl4-openssl-dev protobuf-compiler libprotobuf-dev git
RUN git clone https://github.com/intel/dynamic-application-loader-host-interface.git
WORKDIR dynamic-application-loader-host-interface
RUN cmake .;make;make install;systemctl enable jhi
RUN mkdir /home/user
ADD ./AMCS /home/user/AMCS
ADD ./install-sgx-2.3.sh /
WORKDIR /
ADD ./iclsclient_1.45.449.12-2_amd64.deb /
RUN dpkg -i iclsclient_1.45.449.12-2_amd64.deb 
RUN sed -i 's/sudo //g' /install-sgx-2.3.sh
RUN sed -i 's/--no-install-recommends//g' /install-sgx-2.3.sh
RUN chmod 777 /install-sgx-2.3.sh
WORKDIR /home/user/AMCS/monotonic
RUN make
RUN sed -i 's/log_level RELEASE/log_level DEBUG/g' /etc/jhi/jhi.conf
#RUN sed -i 's/192.168.56.1/127.0.0.1/g' /etc/jhi/jhi.conf
COPY ./start_up.sh .
RUN chmod 666 start_up.sh
CMD /bin/bash ./start_up.sh
#&& /bin/bash -c "sleep 1 && /bin/bash /install-sgx-2.3.sh && source /opt/intel/sgxsdk/environment && /bin/bash"
#CMD /bin/bash

#if $light_debug; then
#    echo "[DEBUG] check on LD_LIBRARY_PATH"; read
#fi
#installing psw/platform services
#cd ../../../..
#if $debug_mode; then
#    echo "[DEBUG] dpkg'ing iclsclient"; read
#fi
#sudo dpkg -i iclsclient_1.45.449.12-2_amd64.deb
#sudo apt install -y uuid-dev libxml2-dev cmake pkg-config libsystemd-dev
#if [ ! -d ./dynamic-application-loader-host-interface ]; then
#    git clone https://github.com/intel/dynamic-application-loader-host-interface.git
#fi
#cd dynamic-application-loader-host-interface
#if $debug_mode; then
#    echo "[DEBUG] jhi making"; read
#fi
#cmake .;make;sudo make install
#echo "[DEBUG] jhi debug done"
#if [ -z "$(pidof /usr/sbin/jhid)" ]; then
#    echo "[DEBUG] jhi pid is "$(pidof /usr/sbin/jhid)
##    sudo jhid 2>&1 &
#fi
##sudo systemctl enable jhi
#cd ..
#cd linux-sgx/linux/installer/deb
#if $light_debug; then
#    echo "[DEBUG] dpkg'ing libsgx"; read
#    echo $LD_LIBRARY_PATH
#fi
#
#sudo LD_LIBRARY_PATH=/home/ubuntu/sgx-install/linux-sgx/linux/installer/bin/sgxsdk/sdk_libs:/home/ubuntu/sgx-install/linux-sgx/linux/installer/bin/sgxsdk/sdk_libs:/home/ubuntu/sgx-install/linux-sgx/linux/installer/bin/sgxsdk/sdk_libs:/opt/Intel/iclsClient/lib dpkg -i libsgx-urts_2.4.100.48163-xenial1_amd64.deb libsgx-enclave-common_2.4.100.48163-xenial1_amd64.deb
#if $light_debug; then
#    echo "[DEBUG] after dpkg"; read
#    echo $LD_LIBRARY_PATH
#fi
#
#if $light_debug; then
#    echo "[DEBUG] start aesmd"; read
#fi
#sudo service aesmd start
